name = 'alt:V Server'
debug = true
host = "0.0.0.0"
port = 7788
players = 128
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
gamemode = 'Freeroam'
website = 'example.com'
language = 'en'
description = 'alt:V Sample Server'
modules = ['csharp-module', 'js-module', 'js-bytecode-module']
resources = ['chat', 'freeroam', 'commands', 'auth-system']